### ISSUE TITLE
Amenities filter disapearing

### ISSUE THREAD

**Issue by lcoenen** [Whichost/frontend#45]
When the mouse is leaving the window opened for the amenities filter, the amenities disappears.
![image](https://user-images.githubusercontent.com/1237971/52574255-cc65f100-2e13-11e9-93aa-47ee24f7d500.png)

**Comment by buckwierd** [comment]
Tested it again. Looks like it was fixed. Thanks!

**Comment by lcoenen** [comment]
It isn't fixed. In chrome, I can replicate the issue in both `master` and `staging`.

**Comment by buckwierd** [comment]
Strange. It was working two days ago perfectly.

**Comment by lcoenen** [comment]
Try it yourself.

**Comment by buckwierd** [comment]
Just did and commented based on that. It’s really strange that it was working after it was reported and now, 2 days later, it’s not working again.

**Comment by lcoenen** [comment]
![image](https://user-images.githubusercontent.com/1237971/52793239-31fcec00-3065-11e9-9c94-74e1c2d41cac.png)

**Comment by lcoenen** [comment]
So this is a known bug from sharetribe: 

![image](https://user-images.githubusercontent.com/1237971/52794602-06c7cc00-3068-11e9-8cc0-609c8aec010e.png)

**Comment by lcoenen** [comment]
![image](https://user-images.githubusercontent.com/1237971/53091479-f1401f80-3509-11e9-8ed1-f4722c396f0c.png)

**Comment by lcoenen** [comment]
This will be fixed with the new merged.
